#!/usr/bin/env python3

"""
Google Translator cmd client.

This will translate arbitary strings in any language using
google translator. (By parsing HTML)"""

from bs4 import BeautifulSoup
from selenium import webdriver
import argparse
import sys
import signal


def getHtml(text, origin_lang='auto', dest_lang='en'):
    driver = webdriver.PhantomJS()
    driver.get('https://translate.google.com/#{origin}/{dest}/{text}'.format(text=text, origin=origin_lang, dest=dest_lang))
    text = driver.page_source
    
    driver.service.process.send_signal(signal.SIGTERM)
    driver.quit()
    
    return text


def filterTranslation(html):
    def processContents(c):
        if c.name == 'br':
            return '\n'
        else:
            return c.contents[0]
    
    soup = BeautifulSoup(html, 'html.parser')
    return ' '.join([processContents(x) for x in soup.find(id='result_box').findChildren()])


def main():
    parser = argparse.ArgumentParser(description='Translate arbitary text in any language.')
    if sys.stdin.isatty():
        parser.add_argument('text', help='Text which should get translated.', default=sys.stdin)

    parser.add_argument('-o', dest='origin_lang', help='Origin language eg. de, en, fr, auto (default: auto)', default='auto')
    parser.add_argument('-d', dest='dest_lang', help='Destination language eg. de, en, fr (default: de)', default='de')
    args = parser.parse_args()

    try:
        text = args.text
    except:
        text = sys.stdin.readlines()[0]
    
    print(filterTranslation(getHtml(text, args.origin_lang, args.dest_lang)))
    

if __name__ == "__main__":
    main()
    

